In [1]:
import numpy as np

In [2]:
#3d array
b = np.array([[[3,4],[6,5]],[[1,5],[9,8]]])
print(b)

[[[3 4]
  [6 5]]

 [[1 5]
  [9 8]]]


# Zeros in 3D

In [3]:
z3 = np.zeros((2,3,4))                            # creating a Zeros array, of 3 dimensions
z3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# Ones in 3D

In [4]:
a3 = np.ones((2,3,4), dtype=int)                            # creating an Ones array, of 3 dimensions
print(a3)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [5]:
np.ndim(a3)                            # checking the dimension of a3

3

In [6]:
a3.size                            # checking the no. of elments in a3

24

In [7]:
np.ones((2,2,2), dtype=str)

array([[['1', '1'],
        ['1', '1']],

       [['1', '1'],
        ['1', '1']]], dtype='<U1')

X = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
Y = np.array([[[10,11,12],[13,14,15],[16,17,18]]])
X
Y

In [11]:

V3 = np.vstack((z3,a3))
print(V3,"\n------------------------------------------------\n",)
H3 = np.hstack((z3,a3))
print(H3)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]] 
------------------------------------------------

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [12]:
x = np.random.randn(2,3,4)                              # a 3-D Random array of shape 2x3x4

In [13]:
np.random.rand(2,3,5)

array([[[0.67311385, 0.54151837, 0.51635245, 0.80271585, 0.03619048],
        [0.15049303, 0.53259891, 0.91598309, 0.71737274, 0.62472315],
        [0.82922557, 0.21345364, 0.28561153, 0.71364029, 0.62917049]],

       [[0.28026256, 0.6138754 , 0.03532703, 0.52520812, 0.06344703],
        [0.64426165, 0.82256745, 0.68107566, 0.40442993, 0.92100491],
        [0.3735936 , 0.82528085, 0.86630663, 0.4798528 , 0.11940836]]])

In [14]:
 #creating a Full array with string datatype, of 3 dimensions, with 'python' at each position

f3 = np.full([2,3,4], 'i love python')
print(f3)

[[['i love python' 'i love python' 'i love python' 'i love python']
  ['i love python' 'i love python' 'i love python' 'i love python']
  ['i love python' 'i love python' 'i love python' 'i love python']]

 [['i love python' 'i love python' 'i love python' 'i love python']
  ['i love python' 'i love python' 'i love python' 'i love python']
  ['i love python' 'i love python' 'i love python' 'i love python']]]


In [15]:
c = np.empty([2, 5, 3])                                     # creating a 3-D Empty array

In [16]:
c = np.empty([2,5,3], dtype=int)                          # creating a 3-D Empty array, with integer datatype

In [17]:
c

array([[[3801155, 5570652, 6619251],
        [7536754, 6946908, 7929953],
        [7012449, 3014748, 7340137],
        [7602297, 7274600, 6029422],
        [7471216, 6684783, 7077993]],

       [[6226021, 6619236, 6357094],
        [7078005, 6029428, 6881384],
        [7602291, 7471215, 3014777],
        [7405683, 6881388, 6619252],
        [7798829, 7077985,       0]]])

In [18]:
c = np.empty([2,5,3], dtype=object)                        # creating a 3-D Empty array, with object datatype
c

array([[[None, None, None],
        [None, None, None],
        [None, None, None],
        [None, None, None],
        [None, None, None]],

       [[None, None, None],
        [None, None, None],
        [None, None, None],
        [None, None, None],
        [None, None, None]]], dtype=object)

#### Transpose of a 3-D array

In [19]:
C = np.array([[[1,2,3],[4,5,6],[7,8,9]]])                 # creating a 3-D array of 1x3x3 elements
C

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [20]:
C.T

array([[[1],
        [4],
        [7]],

       [[2],
        [5],
        [8]],

       [[3],
        [6],
        [9]]])

In [21]:
C = np.array([[ [11,12,13],[14,15,16],[17,18,19]], [[20,21,22],[23,24,25],[26,27,28] ]])