# 2D Numpy in Python


Estimated time needed: **30** minutes
    

## Objectives

After completing this lab you will be able to:

* Operate comfortably with `numpy`
* Perform complex operations with `numpy`


<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li><a href="#Create-a-2D-Numpy-Array">Create a 2D Numpy Array</a></li>
        <li><a href="#Accessing-different-elements-of-a-Numpy-Array">Accessing different elements of a Numpy Array</a></li>
        <li><a href="#Basic-Operations">Basic Operations</a></li>
    </ul>
  
</div>

<hr>


## Create a 2D Numpy Array


In [36]:
# Import the libraries

import numpy as np

Consider the list <code>a</code>, which contains three nested lists **each of equal size**. 


In [37]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

We can cast the list to a Numpy Array as follows:


In [38]:
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

We can use the attribute <code>ndim</code> to obtain the number of axes or dimensions, referred to as the rank. 


In [39]:
# Show the numpy array dimensions

A.ndim

2

Attribute <code>shape</code> returns a tuple corresponding to the size or number of each dimension.


In [40]:
# Show the numpy array shape

A.shape

(3, 3)

The total number of elements in the array is given by the attribute <code>size</code>.


In [41]:
# Show the numpy array size

A.size

9

In [42]:
A.itemsize

4

<hr>


## Accessing different elements of a Numpy Array


We can use rectangular brackets to access the different elements of the array. The correspondence between the rectangular brackets and the list and the rectangular representation is shown in the following figure for a 3x3 array:  


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoEg.png" width="500">


We can access the 2nd-row, 3rd column as shown in the following figure:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFT.png" width="400">


 We simply use the square brackets and the indices corresponding to the element we would like:


In [43]:
# Access the element on the second row and third column

A[1, 2]

23

 We can also use the following notation to obtain the elements: 


In [44]:
# Access the element on the second row and third column

A[1][2]

23

 Consider the elements shown in the following figure 


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFF.png" width="400">


We can access the element as follows: 


In [45]:
# Access the element on the first row and first column

A[0][0]

11

We can also use slicing in numpy arrays. Consider the following figure. We would like to obtain the first two columns in the first row


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFSF.png" width="400">


 This can be done with the following syntax: 


In [46]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

Similarly, we can obtain the first two rows of the 3rd column as follows:


In [47]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])

Corresponding to the following figure: 


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/2D_numpy.png" width="400"><br />


In [48]:
A[0,-1]

13

In [49]:
print(A[0])

[11 12 13]


In [50]:
#print(a[0,:])

In [51]:
#print(a[:,0])

## Basic Operations


We can also add arrays. The process is identical to matrix addition. Matrix addition of <code>X</code> and <code>Y</code> is shown in the following figure:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoAdd.png" width="500">


The numpy array is given by <code>X</code> and <code>Y</code>


In [52]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [53]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

 We can add the numpy arrays as follows.


In [54]:
# Add X and Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

Multiplying a numpy array by a scaler is identical to multiplying a matrix by a scaler. If we multiply the matrix <code>Y</code> by the scaler 2, we simply multiply every element in the matrix by 2, as shown in the figure.


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoDb.png" width="500">


We can perform the same operation in numpy as follows 


In [55]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [56]:
# Multiply Y with 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

Multiplication of two arrays corresponds to an element-wise product or <em>Hadamard product</em>. Consider matrix <code>X</code> and <code>Y</code>. The Hadamard product corresponds to multiplying each of the elements in the same position, i.e. multiplying elements contained in the same color boxes together. The result is a new matrix that is the same size as matrix <code>Y</code> or <code>X</code>, as shown in the following figure.


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoMul.png" width="500">


We can perform element-wise product of the array <code>X</code> and <code>Y</code> as follows:


In [57]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [58]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [59]:
# Multiply X with Y

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

We can also perform matrix multiplication with the numpy arrays <code>A</code> and <code>B</code> as follows:


First, we define matrix <code>A</code> and <code>B</code>:


In [60]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [61]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

We use the numpy function <code>dot</code> to multiply the arrays together.


In [62]:
# Calculate the dot product

Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [63]:
# Calculate the sine of Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

We use the numpy attribute <code>T</code> to calculate the transposed matrix


In [64]:
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [65]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])

In [66]:
np.transpose(A)             # alternate command to transpose

array([[0, 1],
       [1, 0],
       [1, 1]])

In [67]:
B = np.array([[11,12,13,14],[15,16,17,18]])
B
B[:]

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [68]:
B[B>14]
B[B<14]

array([11, 12, 13])

#### Ones Like Array - It returns an array of Ones, with the same shape & type as of the given array.
#### Syntax :
    np.ones_like(array, dtype)

In [69]:
D = np.ones_like(C)                                 # creating an Ones array, from array C
D

array([[1, 1],
       [1, 1],
       [1, 1]])

In [70]:
D = np.ones_like(C, dtype=int)                     # creating an Ones array of Integer datatype, from array C
D

array([[1, 1],
       [1, 1],
       [1, 1]])

## zeros in 2D

In [71]:
z2 = np.zeros((3,4))                           # creating a Zeros array, of 2 dimensions
z2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
z2 = np.zeros((3,4), dtype=int)                    # creating a Zeros array, of 2 dimensions, with data-type as integer
z2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## Ones in 2D

In [73]:
a2 = np.ones((2,3))                           # creating an Ones array, of 2 dimensions
print(a2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [74]:
a2 = np.ones((2,3), dtype=int)                    # creating an Ones array, of 2 dimensions, with data-type as integer
print(a2)

[[1 1 1]
 [1 1 1]]


## FULL IN 2D

In [75]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [76]:
np.full((3,3),3,dtype = 'float32')

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]], dtype=float32)

#### Random Function

It returns random float number(s) between 0 and 1.

In [77]:
#ramdom decimals
np.random.rand(4,2)

array([[0.76604052, 0.89623458],
       [0.28441343, 0.25205511],
       [0.89713874, 0.0424313 ],
       [0.08228629, 0.19237003]])

In [78]:
np.random.random((2,3))

array([[0.57877899, 0.49332574, 0.18408012],
       [0.43082893, 0.26752795, 0.53677757]])

In [79]:
a=np.array([[10, 21, 12,  1,  8,  9, 12],[12,  1,  2,  2,  9,  6,  5]])

In [80]:
a

array([[10, 21, 12,  1,  8,  9, 12],
       [12,  1,  2,  2,  9,  6,  5]])

In [81]:
np.random.random_sample(a.shape)

array([[0.53389071, 0.99263151, 0.3636067 , 0.72517696, 0.92655354,
        0.36342283, 0.14440279],
       [0.40475416, 0.67016711, 0.46532834, 0.37625496, 0.48221431,
        0.53273068, 0.40363024]])

In [82]:
np.random.rand(2,3)

array([[0.4353412 , 0.61500234, 0.00363484],
       [0.43427941, 0.41329375, 0.85684848]])

In [83]:
np.random.randn(3,5)

array([[-0.41042571,  1.07289325,  0.41166924, -0.13605297,  1.03535298],
       [ 0.58529451,  0.44853939, -1.51930771,  0.27986851,  0.42904717],
       [ 0.08788664,  0.44992525, -0.26134378, -0.24315847, -1.14179639]])

In [84]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [85]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [86]:
np.identity(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

##### The Eye Function returns a 2-D array , with 1 on diagonal and 0 elsewhere.
###### Syntax :
    np.eye(shape, k, dtype)

- Here, if only No. of Rows is passed, then No. of Columns = No. of Rows
- K is Index of diagonal, by default, k=0 means Main diagonal ; when k=positive means Upper diagonal ; when k=negative means Lower diagonal
- The default datatype is float

In [87]:
A = np.eye(4)                                         # creating an array of shape 4x4
A

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [88]:
A = np.eye(4, k=0)                                    # creating an array of shape 4x4, with 1 at Main diagonal
A

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [89]:
B = np.eye(4, k=1)                                    # creating an array of shape 4x4, with 1 at Upper diagonal
B

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [90]:
C = np.eye(4, k=-1)                                   # creating an array of shape 4x4, with 1 at Lower diagonal
C

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [91]:
D = np.eye(4, dtype=int)                              # creating an array of shape 4x4, with Integer datatype
D

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [92]:
E = np.eye(4, 5)                                       # creating an array of shape 4x5  (k=0)
E

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [93]:
F = np.eye(5, 4)                                      # creating an array of shape 5x4   (k=0)
F

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [94]:
np.eye(1)

array([[1.]])

In [95]:
np.eye(12)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [96]:
np.eye(6,9, k=3, dtype=int)

array([[0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [97]:
a = np.eye(5, dtype=str)
a

array([['1', '', '', '', ''],
       ['', '1', '', '', ''],
       ['', '', '1', '', ''],
       ['', '', '', '1', ''],
       ['', '', '', '', '1']], dtype='<U1')

In [98]:
b1 = np.array([[2,4,6,8],[1,3,5,7]])
b1

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [99]:
a1 = b1.reshape((4,2))
a1

array([[2, 4],
       [6, 8],
       [1, 3],
       [5, 7]])

In [100]:
s = np.array([[1,2,3],[4,5,6]])
np.sum(s)
np.sum(s, axis = 1)

array([ 6, 15])

In [101]:
a = np.full((3,4),5)
b = np.full((4,5),4)
print(a)
print(b)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


In [102]:
np.matmul(a,b)

array([[80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80]])

In [103]:
c = np.identity(5)

In [104]:
np.linalg.det(c)

1.0

In [105]:
P = np.array([[1,2,3,4],[5,6,7,8]])
P

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [106]:
Q = np.array([[9,10,11,12],[13,14,15,16]])
Q

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [107]:
V2 = np.vstack((P,Q))
V2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [108]:
H2 = np.hstack((P,Q))
H2

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [109]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])                      # creating a 2-D array of 3x3
A
np.diag(A)                                       # extracting the diagonal elements of array 'A'

array([1, 5, 9])

In [110]:
np.diag(A, k=0)                                     # when k=0, it will consider the main diagonal
np.diag(A, k=2)                                     # when k>0, it will consider the upper diagonal
np.diag(A, k=-2)                                   # when k<0, it will consider the lower diagonal

array([7])

## Empty array

In [111]:
b = np.empty((5, 3))                                      # creating a 2-D Empty array
b

array([[0.41042571, 1.07289325, 0.41166924],
       [0.13605297, 1.03535298, 0.58529451],
       [0.44853939, 1.51930771, 0.27986851],
       [0.42904717, 0.08788664, 0.44992525],
       [0.26134378, 0.24315847, 1.14179639]])

In [112]:
b = np.empty((5,3), dtype=int)                           # creating a 2-D Empty array, with integer datatype
b

array([[      0,       0,       0],
       [      0,       0,       0],
       [      0,       0,       0],
       [      0,    1188,       0],
       [      0, 4980828,       0]])

In [113]:
b  = np.empty((5,3), dtype=object)                        # creating a 2-D Empty array, with object datatype
b

array([[None, None, None],
       [None, None, None],
       [None, None, None],
       [None, None, None],
       [None, None, None]], dtype=object)

## Quiz on 2D Numpy Array


Consider the following list <code>a</code>, convert it to Numpy Array. 


In [114]:
# Write your code below and press Shift+Enter to execute

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

<details><summary>Click here for the solution</summary>

```python
A = np.array(a)
A
```

</details>


Calculate the numpy array size.


In [115]:
# Write your code below and press Shift+Enter to execute


<details><summary>Click here for the solution</summary>

```python
A.size
```

</details>


Access the element on the first row and first and second columns.


In [116]:
# Write your code below and press Shift+Enter to execute


<details><summary>Click here for the solution</summary>

```python
A[0][0:2]
```

</details>


Perform matrix multiplication with the numpy arrays <code>A</code> and <code>B</code>.


In [117]:
# Write your code below and press Shift+Enter to execute

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

<details><summary>Click here for the solution</summary>

```python
X = np.dot(A,B)
X
```

</details>
