In [1]:
#Boolean indexing
import numpy as np
ar = np.array([1,5,3,6,4])
ar[ar > 4] = 40
print(ar)

[ 1 40  3 40  4]


In [2]:
# a = np.array([1,2,3,4,5]) # 1, 5
# b = np.array([3,4,5,6,7,10]) # 1, 6
# a = np.array([ # 2,2 
#     [1,2],
#     [3,4]
# ])

# b = np.array([
#     [5,2,5],      #2,3
#     [6,4,6]
# ])

# result = a + b
# print(result)

# Shape (1, 3) and shape (4, 3)
# Shape (2, 1) and shape (2, 3)
# Shape (1, 1) and shape (3, 1)

a1= np.array([
    [1,3,4]
])
a2 = np.array([
    [3,4,5],
    [1,2,3],
    [4,5,6],
    [6,7,8]
])
# print(a1 + a2)
s = 10
new_ar = a2 + 10
print(new_ar)

[[13 14 15]
 [11 12 13]
 [14 15 16]
 [16 17 18]]


In [3]:

ar = np.array([
    [1,2,3],
    [5,6,7]
])
for i, v in np.ndenumerate(ar):
    print(i, v)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 5
(1, 1) 6
(1, 2) 7


In [4]:

ar = np.array([
    [1,2,3],
    [2,1,4,] 
]) # (2,3) 2D
for i in np.nditer(ar, order="F"):
    print(i)

1
2
2
1
3
4


In [5]:

a = np.array([3,4,6])
# mean()
# median()
# var()
# std()
# min()
# max()
# sum()
# prod()
# argmin()
# argmax()
print(np.argmax(a))

2


In [6]:
ar = np.array([0,1,2,3, 0, 0, 0, 3,4, 1,1,2,10])
# count_nonzero()
# unique()
# bincount()
# sum()
# cumsum()
# prod()
# cumprod()
result = np.cumprod(ar)
print(result)

[0 0 0 0 0 0 0 0 0 0 0 0 0]


In [7]:

a = np.array([1,2,3])
b = np.array([4,5,6])

# add
# subtract
# multiply
# divide
# floor_divide
# power
# mod 
# remainder
# reciprocal 
# negative
# abs
# print((np.power(a,b)))

n1 = np.array([-4,-7,9]) # 1/4, 1/7, 1/9
n2 = np.array([2,3,5])
print(np.remainder(n1,n2)) # 0, 1, 4
print(np.reciprocal(n1)) 
print(np.negative(n1))
print(np.abs(n1))



[0 2 4]
[0 0 0]
[ 4  7 -9]
[4 7 9]


In [8]:
ar = np.array([3,1,2,4,7,0])
arg_sorted_ar = np.argpartition(ar, 3) # 1,2,0 3 4, 7
print("Arg Partision")
print(arg_sorted_ar)


Arg Partision
[1 5 2 0 3 4]


In [9]:
import numpy as np 
ar = np.array([2,3,0,1])
print("Before sorting")
print(ar)
print("After sorting")
print(np.sort(ar))
print("Showing their index numbers")
print(np.argsort(ar))

Before sorting
[2 3 0 1]
After sorting
[0 1 2 3]
Showing their index numbers
[2 3 0 1]


In [10]:
ar = np.array([1,2,3,4,5,6,7,8,9,10])
i = np.argwhere(ar > 3)
print(i)

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [11]:
ar = np.array([1,2,3,4,5,6,46,7,8,9,0,10,12,13])
mask = ar != 6
print(ar[mask])

[ 1  2  3  4  5 46  7  8  9  0 10 12 13]


In [12]:
ar = np.array([1,2,3,4,5,6,7,8,9,10])
arr = np.compress(ar<3, ar)
print(arr)

[1 2]


In [13]:
ar = np.array([1,2,3,4,5,6,7,8,9,10])
arr = np.extract(ar>3, ar)
print(arr)

[ 4  5  6  7  8  9 10]


In [14]:
ar = np.array([1,2,3,4,5,6,7,8,9,10])
arr = np.extract(ar!=3, ar)
print(arr)

[ 1  2  4  5  6  7  8  9 10]


In [15]:
ar = np.array([11,12,3,4,5,6,7,8,1,10,100,2,6])
new_arr = np.where(ar > 3, ar, 0)
print(new_arr)

[ 11  12   0   4   5   6   7   8   0  10 100   0   6]


In [16]:
ar = np.array([1,2,0,0,8,0])
nonzero = np.nonzero(ar)
print(nonzero)

(array([0, 1, 4], dtype=int64),)


In [17]:
ar = np.array([1,2,3,4, 5, 6, 8])
i = np.searchsorted(ar, 7)
print(i)

6


In [18]:
ar = np.array([
    [1, 0],
    [5, 3]
])
sorted_ar = np.sort(ar, axis=1)
print(sorted_ar)

[[0 1]
 [3 5]]


In [19]:
ar = np.array([1,2,3,4,5,6,7,8,9,10])
i = np.where(ar > 3)
print(i)

(array([3, 4, 5, 6, 7, 8, 9], dtype=int64),)


In [20]:
orignal = np.array([1,2,3,4,5,6,7,8,9,10])
cpy = orignal.copy()
cpy[0] = 1000
print(cpy)
print(orignal)


[1000    2    3    4    5    6    7    8    9   10]
[ 1  2  3  4  5  6  7  8  9 10]


In [21]:
ar = np.array([1,2,3,4,5,6,7,8,9,10])
# i = [3,0,1]
# new_ar = ar[i]
# new_ar[0] = 400
# print(new_ar)
# print(ar)

# Boolean indexing 
new_copy_ar = ar[ar > 5]
new_copy_ar[0] =  6000
print(new_copy_ar)
print(ar)

[6000    7    8    9   10]
[ 1  2  3  4  5  6  7  8  9 10]


In [22]:
orignal = np.array([1,2,3,4,5,6,7,8,9,10])
view = orignal[1:5]
view[0] = 300
print(orignal)

[  1 300   3   4   5   6   7   8   9  10]


In [23]:
ar1 = np.array([1,2,3,4,5,6])
view2 = ar1.reshape(2,3)
view2[0,0] = 1000
print(view2)
print(ar1)

[[1000    2    3]
 [   4    5    6]]
[1000    2    3    4    5    6]
